### ISSUE TITLE
Start Timer has undefined behaviour on first click.

### ISSUE THREAD

**Issue by Balaguru4580** [Balaguru4580/pomodorset#2]
Upon pressing the Start Timer button, the timer shows the following

![issue](https://user-images.githubusercontent.com/61746056/134658692-f998104e-4615-4228-a13e-1f85bd9238c0.JPG)

However, upon second click, the appropriate behaviour is seen. 

Not sure what the issue is, but there's a good chance it has something to do with passing the input field data to the Timer component, from the Crucials component.

**Comment by Kapil-Kawathekar** [comment]
@Balaguru4580  Hii , I have resolved that NAN problem , but apart from that I want to know if user submit empty form then we can take 0:0:0 as default timer value instead of starting 15 min default timer because then user will get confused when 15 min timer start on second click so basically we set this as 0:0:0 until user enter the correct data in form, then ,  what do you think ?? let me know then I will create the Pull request with this update.

**Comment by Balaguru4580** [comment]
Sounds like a good idea. The 15 min timer start was actually for me to debug it easily without having to enter values every time. 

Additionally, instead of setting to 0:0:0, we can just have an error pop up for the user to enter the requested time instead. Might be a good PR for a beginner! 

Please make your pull request after October 1st for it to be valid Hacktoberfest. Also, ensure it follows the guidelines in the [CONTRIBUTING doc](https://github.com/Balaguru4580/pomodorset/blob/main/CONTRIBUTING.md)  

Appreciate the help. Thanks a lot!

**Comment by Kapil-Kawathekar** [comment]
Yeah I will provide alert pop up message to enter the valid time and yeah will create the PR on 1st of October so it will counted in Hacktober-Fest😁
